import fs from 'fs'; import path from 'path'; import { spawn } from 'child_process';
const MOD=(process.env.MODULE_NUM||'00').toString().padStart(2,'0'); const PORT=String(process.env.PORT||5050); const base=`http://127.0.0.1:${PORT}/api/v1`;
const logsDir=path.resolve(process.cwd(),'logs'); if(!fs.existsSync(logsDir)) fs.mkdirSync(logsDir,{recursive:true});
const logName= MOD==='07' ? 'mod-07.log' : `selftest.mod-${MOD}.log`; const jsonName=`selftest.mod-${MOD}.json`; const logPath=path.join(logsDir,logName); const jsonPath=path.join(logsDir,jsonName);
const log=(s)=>fs.appendFileSync(logPath,s+'\n'); const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
async function req(url,init){ const r=await fetch(url,init); let body=null; try{ body=await r.clone().json(); }catch{} return { r, body }; }
async function start(){ log(`[selftest m${MOD}] starting server...`); const dist=path.resolve(process.cwd(),'dist','index.js'); if(!fs.existsSync(dist)){ await new Promise(res=> spawn('npm',['run','build'],{stdio:'inherit'}).on('close',res)); } const env={...process.env, PORT, NODE_ENV:'test'}; const srv=spawn('node',['dist/index.js'],{env}); srv.stdout.on('data',d=>log(String(d).trim())); srv.stderr.on('data',d=>log(String(d).trim())); await wait(1200); return srv; }
async function run07(result){ const email=`m07_${Date.now()}@example.com`; const name='Test Person'; let r=await req(`${base}/profiles`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,email,headline:'Demo'})}); result.checks.push({name:'profiles.create', ok:r.r.status===201, status:r.r.status}); let s=await req(`${base}/profiles?q=Test`); const found=Array.isArray(s.body?.items)? s.body.items.some(p=>p.email===email): Array.isArray(s.body)? s.body.some(p=>p.email===email): false; result.checks.push({name:'profiles.search', ok:s.r.status===200 && found, status:s.r.status}); const profileId=r.body?.profile?.id; let iv=await req(`${base}/interviews`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profileId, title:'Intro Call'})}); result.checks.push({name:'interviews.create', ok:iv.r.status===201, status:iv.r.status}); let il=await req(`${base}/interviews?profileId=${profileId}`); const ilok=il.r.status===200 && (Array.isArray(il.body?.items)? il.body.items.some(x=>x.profileId===profileId): Array.isArray(il.body)? il.body.some(x=>x.profileId===profileId): false); result.checks.push({name:'interviews.list', ok:ilok, status:il.r.status}); for(let i=0;i<30;i++){ await req(`${base}/profiles`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:`User ${i}`, email:`u${Date.now()}_${i}@example.com`})}); } let p1=await req(`${base}/profiles?limit=20`); let next=p1.body?.nextCursor; const a=(p1.body?.items||[]).map(x=>x.id); let p2=await req(`${base}/profiles?limit=20&cursor=${encodeURIComponent(next||'')}`); const b=(p2.body?.items||[]).map(x=>x.id); const dupes=a.filter(x=>b.includes(x)); result.checks.push({name:'profiles.pagination', ok:p1.r.status===200 && p2.r.status===200 && (p2.body?.items||[]).length>0 && dupes.length===0, status:`${p1.r.status}/${p2.r.status}`}); let dup=await req(`${base}/profiles`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name, email})}); result.checks.push({name:'profiles.duplicate', ok:dup.r.status===409, status:dup.r.status}); }
async function main(){ const result={checks:[], passed:false, ts:new Date().toISOString(), module:MOD}; const srv=await start(); if(MOD==='07'){ try{ await run07(result);}catch(e){ for(const n of ['profiles.create','profiles.search','interviews.create','interviews.list','profiles.pagination','profiles.duplicate']) result.checks.push({name:n, ok:false, error:String(e)}); } } log('[selftest] building client...'); const b=spawn('npm',['run','build']); b.stdout&&b.stdout.on('data',d=>log(String(d).trim())); b.stderr&&b.stderr.on('data',d=>log(String(d).trim())); await new Promise(res=>b.on('close',res)); result.checks.push({name:'client.build', ok:b.exitCode===0}); srv.kill('SIGINT'); result.passed=result.checks.every(c=>c.ok); fs.writeFileSync(jsonPath, JSON.stringify(result,null,2)); console.log(result.passed?'ALL CHECKS PASSED':'CHECKS FAILED, see logs/selftest.*'); process.exit(result.passed?0:1); }
main();
