import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const app = express();
app.use(express.static(process.cwd(), { extensions: ['html'] }));
app.get('/', (req,res)=> res.sendFile(path.resolve(process.cwd(), 'home.html')));
const port = process.env.PORT || 3000;
app.listen(port, ()=> console.log('server http://localhost:'+port));